#!/bin/sh
set -e
for GROUP in fuse; do
  adduser $ACCOUNT $GROUP || true
done
for GROUP in cdrom floppy audio dip video plugdev; do
  deluser $ACCOUNT $GROUP || true
done
perl -pi -e 's/USERGROUPS=yes/USERGROUPS=no/' /etc/adduser.conf
perl -pi -e "s/^${ACCOUNT}:x:1000:1000/${ACCOUNT}:x:1000:100/" /etc/passwd
find ${ACCOUNTHOME} -gid 1000 -print0|xargs -0 --no-run-if-empty chown ${ACCOUNT}:users
delgroup ${ACCOUNT}||true
