#!/bin/sh
set -e
cd /etc
FILES="packages/list packages/manual"
cleanup () {
	if [ -n "$logfile" ]; then
		rm -f "$logfile"
	fi
}
if [ -n "$1" ]; then
	trap cleanup EXIT
	logfile="$(mktemp -t etckeeper-$VCS.XXXXXXXXXX)"
	if [ "x$1" = "x--stdin" ]; then
		cat > "$logfile"
	else
		if [ "x$1" = "x-m" ]; then
			shift 1
		fi
		echo "$1" > "$logfile"
	fi
else
	logfile=""
fi

hostname=`hostname`
hostname="${hostname%%.*}"
dnsdomainname=`dnsdomainname 2>/dev/null || true`
if [ -n "$dnsdomainname" ]; then
	hostname="$hostname.$dnsdomainname"
fi

USER=
if [ -n "$SUDO_USER" ]; then
	USER="$SUDO_USER"
else
	# try to check tty ownership, in case user su'd to root
	TTY="$(tty 2>/dev/null || true)"
	if [ -n "$TTY" ] && [ -c "$TTY" ]; then
		USER="$(find "$TTY" -printf "%u")"
	fi
fi

if [ "$VCS" = git ] && [ -d .git ]; then
	if [ -n "$USER" ]; then
		if [ -z "$GIT_AUTHOR_NAME" ]; then
			export GIT_AUTHOR_NAME="$USER"
		fi
		if [ -z "$GIT_AUTHOR_EMAIL" ]; then
			export GIT_AUTHOR_EMAIL="$USER@$hostname"
		fi
		if [ -z "$GIT_COMMITTER_EMAIL" ]; then
			export GIT_COMMITTER_EMAIL=`whoami`"@$hostname"
		fi
	fi
	if [ -n "$logfile" ]; then
		git commit $GIT_COMMIT_OPTIONS -F "$logfile" -- $FILES
	else
		git commit $GIT_COMMIT_OPTIONS -- $FILES
	fi
fi
